#!/bin/sh
# This script is only used for developement. It is removed by the
# distribution process.

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -classic-display \
                          -use-ocamlfind"}

action ()
{
    case $1 in
        default) topkg build ;;
        download-test-files)
            # FIXME this should source from UNICODE_VERSION
            curl -# -S \
         "http://www.unicode.org/Public/UCD/latest/ucd/NormalizationTest.txt" \
            > test/NormalizationTest.txt
            ;;
        test)      topkg build && topkg test -- test/NormalizationTest.txt ;;
        doc)       shift; topkg doc --dev $* ;;
        api-doc)   shift; topkg doc $* ;;
        support)   ocaml "pkg/build_support.ml" ;;
        clean)     topkg clean
                   rm -f src/uunf_data.ml
                   ;;
        *)         $OCAMLBUILD $* ;;
    esac
}

check_db ()
{
    if [ ! -f "support/ucd.xml" ]; then
        echo "Missing unicode character database support/ucd.xml, see DEVEL.md"
        exit 1
    fi
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
