#!/bin/sh

# Usage: build has_native has_uutf

set -e 
LOC=`dirname $0`

. $LOC/pkg-builder

NATIVE=$1
UUTF=$2

add lib pkg/META                
add lib src/uunf.mli      
add lib src/uunf.cmi
add lib src/uunf.cmx
add lib src/uunf.cma
add lib src/uunf.a
add lib src/uunf.cmxa
add lib src/uunf.cmxs

add doc README.md
add doc CHANGES.md
add doc DEVEL.md

if [ "$UUTF" != "false" ]; then 
    add bin test/unftrip
fi

build
install uunf
